const commentBody = [
	"This is some awesome thinking!",
	"What terrific math skills you’re showing!",
	"You are an amazing writer!",
	"Wow! You have improved so much!",
	"Nice idea!",
	"You are showing excellent understanding!",
	"This is clear, concise, and complete!",
	"What a powerful argument!",
	"I knew you could do it!",
	"Wonderful ideas!",
	"It was a pleasure to grade this!",
	"Keep up the incredible work!",
	"My goodness, how impressive!",
	"You’re showing inventive ideas!",
	"You’ve shown so much growth!",
	"Interesting thoughts!",
	"I love your neat work!",
	"Doesn’t it feel good to do such great work?",
	"First-rate work!",
	"This is fascinating information!",
	"You inspire me!",
	"This is right on target!",
	"What an astounding observation!",
	"This is very well thought out!",
	"I can tell you’ve been practicing!",
	"You’ve come a long way!",
	"I can tell you’ve been paying attention!",
	"Reading this made my day!",
	"This is very perceptive!",
	"What an accomplishment!",
	"You make a great point here!",
	"I really like your creativity!",
	"You are an exceptional student!",
	"You have brilliant thoughts!",
	"This is beautiful!",
	"Dazzling examples!",
	"Vivid language choices!",
	"You express your ideas so well!",
	"This was a delight to read!",
	"This is a persuasive argument!",
	"You show an impressive grasp on this subject!",
	"You are gifted!",
	"You are so clever!",
	"What a great learner you are!",
	"I value these thoughts!",
	"You are such a motivated worker!",
	"You show great attention to detail!",
	"You are so artistic!",
	"I am so proud of you!",
	"Lovely handwriting!",
	"Great example!",
	"You worked so hard!",
	"You are a star!",
	"You learned so much!",
	"You are so smart!",
	"You’ve made a lot of progress!",
	"What bright thinking!",
	"You rocked this!",
	"Great thinking!",
	"You did your best!",
	"I love this!",
	"You can do hard things!",
	"You are talented!",
	"You amaze me!",
	"You discovered something new!",
	"I enjoyed reading this!",
	"You are so ambitious!",
	"I appreciate your hard work!",
	"This is magical work!",
	"You did it!",
	"You’ve achieved so much!",
	"You really challenged yourself!",
	"I admire you!",
	"You are unstoppable!",
	"You have great ideas!",
	"This really sparkles!",
	"What a great vision you have!",
	"You have really improved!",
	"You’ve really grown!",
	"You are a snappy problem-solver!",
	"This really shines!",
	"You make me want to learn more!",
	"This made me smile!",
	"You are a winner!",
	"I love your creativity!",
	"You are so intelligent!",
	"You should be proud!",
	"You have amazing potential!",
	"This is top-notch!",
	"You deserve a high five!",
	"Way to think it through!",
	"This blew me away!",
	"These are fabulous ideas!",
	"This gets my seal of approval!",
	"This is quality work!",
	"You reached your goal!",
	"Out of this world!",
	"You’re on top of it!",
	"I can tell this is your best effort!",
	"I love how motivated you are!"
];

module.exports = commentBody;